# Generated by Django 2.2.7 on 2020-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdno', models.IntegerField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('contactno', models.IntegerField(max_length=10)),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('mechanical', 'MECHANICAL'), ('civil', 'CIVIL')], max_length=20)),
                ('passout_year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=20)),
            ],
        ),
    ]
