# Generated by Django 2.2.7 on 2020-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_sec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='regdno',
            field=models.IntegerField(unique=True),
        ),
    ]
